name: Katalon API Tests CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  katalon-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Katalon Studio
      run: |
        wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.4.0/Katalon_Studio_Engine_Linux_64-8.4.0.tar.gz
        tar -xzf Katalon_Studio_Engine_Linux_64-8.4.0.tar.gz -C /opt
        sudo ln -s /opt/Katalon_Studio_Engine_Linux_64-8.4.0/katalonc /usr/local/bin/katalonc

    - name: Activate Katalon Studio
      run: katalon -apikey ${{ secrets.KATALON_API_KEY }} -activate
    
    - name: Run Katalon Studio API Tests
      run: |
        katalonc -noSplash -runMode=console -projectPath=$(pwd)/reqresin.qoinTest1.prj -retry=0 -testSuitePath="Test Suites/Reqres.inTestSuite.ts" -executionProfile="QA" -browserType="Web Service"
